[tool.poetry]
name = "nonebot_plugin_arcaeabot"
version = "0.2.8"
description = "An arcaea plugin for nonebot2. ( A cross platform Python async bot framework. )"
authors = ["Chendihe4975 <Chendihe4975@gmail.com>", "<SEAFHMC> d1366160279@gmail.com"]
license = "AGPL-3.0 License"

[tool.poetry.dependencies]
python = "^3.8"
aiohttp = "^3.8.1"
websockets = "^10.2"
Pillow = "^9.0.1"
peewee = "^3.14.10"
Brotli = "^1.0.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
