[tool.poetry]
name = "nonebot_plugin_arcaeabot"
version = "1.1.0"
description = "An arcaea plugin for nonebot2. ( A cross platform Python async bot framework. )"
authors = ["SEAFHMC <d1366160279@gmail.com>"]
license = "AGPL-3.0 License"

[tool.poetry.dependencies]
python = "^3.8"
nonebot2 = ">=2.0.0-beta.1, <=2.0.0-beta.2"
nonebot-adapter-onebot = ">=2.0.0-beta.1, <=2.0.0-beta.2"
websockets = "^10.0"
Pillow = ">=8.3.1"
peewee = ">=3.14.4"
Brotli = "^1.0.9"
httpx = ">=0.20.0, <1.0.0"
tqdm = "^4.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
